import Banner from "@/sections/Banner";
import Contact from "@/sections/Contact";
import HeaderSection from "@/sections/HeaderSection";
import Introduce from "@/sections/Introduce";
import ListProject from "@/sections/ListProject";
import Papper from "@/sections/Papper";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid bg-white">
        {/* header */}
        <HeaderSection />
        {/* banner */}
        <Banner />
        {/* Introduce */}
        <Introduce />
        {/* List components */}
        <ListProject />
        {/* Papper */}
        <Papper />
        {/* Contact */}
        <Contact />
      </div>
    </>
  );
}
